config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'search', to: 'home#search'

  devise_for :recruiters, controllers: { registrations: 'recruiters/registrations' }
  resources :recruiters, only: %i[index]

  devise_for :candidates, controllers: { registrations: 'candidates/registrations' }
  resources :candidates, only: %i[index]
  
  resources :companies, except: [:new, :create, :destroy]
  resources :jobs, except: [:destroy] do
    shallow do
      resources :job_applications, except: [:edit, :update] do
        resources :rejections, only: [:index, :new, :create]
        resources :offers, only: [:show, :new, :create] do
          post 'accept', on: :member
          resources :denials, only: [:show, :new, :create]
        end
      end
    end
    post 'disable', on: :member
    post 'enable', on: :member
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  has_many :job_applications, dependent: :destroy
  has_many :candidates, through: :job_applications

  validates :title, :description, :remuneration, :level, :requirements,
            :expiration_date, :spots_available, presence: true
  validate :remuneration_cannot_be_less_than_minimum_wage,
           :expiration_date_cannot_be_in_the_past,
           :spots_cannot_be_negative
  after_find :spots_unavailable

  enum status: { enabled: 0, disabled: 1 }, _default: 'enabled'

  def remuneration_cannot_be_less_than_minimum_wage
    if remuneration.present? && remuneration < 1100
      errors.add(:remuneration,
                 :minimum_wage)
    end
  end

  def expiration_date_cannot_be_in_the_past
    if expiration_date.present? && expiration_date < Time.zone.today
      errors.add(:expiration_date,
                 :past_expiration)
    end
  end

  def spots_cannot_be_negative
    if spots_available.present? && spots_available < 1
      errors.add(:spots_available,
                 :negative_spots)
    end
  end

  def spots_unavailable
    hires = job_applications.filter do |application|
      application&.offer&.accepted?
    end
    disabled! if hires.size >= spots_available
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[show edit update disable enable]
  before_action :authenticate_recruiter!, except: %i[index show]
  def index
    @jobs = Job.all
  end

  def show
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    @job.company = current_recruiter.company

    if @job.save
      flash[:notice] = 'Vaga publicada com sucesso'
      @job.enabled!
      redirect_to @job
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @job.update(job_params)
      flash[:notice] = 'Vaga editada com sucesso'
      redirect_to @job
    else
      render 'edit'
    end
  end

  def disable
    @job.disabled!
    redirect_to @job
  end

  def enable
    @job.enabled!
    redirect_to @job
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :remuneration,
                                :level, :requirements, :expiration_date,
                                :spots_available)
  end

  def set_job
    @job = Job.find(params[:id])
  end
end

app/views/jobs/_form.html.erb
<% if @job.errors.any? %>
  <% if @job.persisted? %>
    <p>Não foi possível editar a vaga</p>
  <% else %>
    <p>Não foi possível criar a vaga</p>
  <% end %>

  <p>Confira os erros abaixo:</p>
    <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    
  <% end %>

<%= form_with model: @job do |form| %>
  <div class="field">
    <%= form.label :title, "Título" %>
    <%= form.text_field :title %>
  </div>
    
  <div class="field">
    <%= form.label :description, "Descrição" %>
    <%= form.text_area :description, size: "70x5" %>
  </div>
    
  <div class="field">
    <%= form.label :requirements, "Requisitos obrigatórios" %>
    <%= form.text_area :requirements, size: "70x5" %>
  </div>
    
  <div class="field">
    <%= form.label :level, "Nível do cargo" %>
    <%= form.text_field :level %>
  </div>

  <div class="field">
    <%= form.label :remuneration, "Oferta de remuneração" %>
    <%= form.text_field :remuneration %>
    </div>

  <div class="field">
    <%= form.label :spots_available, "Vagas disponíveis" %>
    <%= form.number_field :spots_available, in: 1..20 %>
  </div>
    
  <div class="field">
    <%= form.label :expiration_date, "Data limite para envio de candidaturas" %>
    <%= form.text_field :expiration_date %>
  </div>

  <div class="actions">
    <%= form.submit "Salvar" %>
  </div>

  <% end %>

app/views/jobs/edit.html.erb
<h1>Editar vaga</h1>

<%= render 'form', job: @job %>

<%= link_to 'Voltar', company_path(current_recruiter.company) %>

app/views/jobs/index.html.erb
<h1 class="display-4 text-center mt-3">Vagas</h1>

<div class="container mt-5">
  <% if @jobs.empty? %>
    <p>Nenhuma vaga encontrada</p>
  <% else %>
    <% @jobs.each do |job| %>
      <% unless job.disabled? %>
        <dl>
          <dt><%= Job.human_attribute_name(:title) %></dt>
          <dd>
            <%= link_to job.title, job_path(job) %>
            @ <%= link_to job.company.name, company_path(job.company) %>
          </dd>

          <dt><%= Job.human_attribute_name(:description) %></dt>
          <dd><%= job.description %></dd>

          <dt><%= Job.human_attribute_name(:level) %></dt>
          <dd><%= job.level %></dd>
        </dl>
        <hr>
      <% end %>
    <% end %>
    <%= link_to 'Voltar', root_path %>
  </div>
<% end %>

app/views/jobs/new.html.erb
<h1>Nova vaga</h1>

<%= render 'form', job: @job %>

<%= link_to 'Voltar', company_path(current_recruiter.company) %>

app/views/jobs/show.html.erb
<% if flash[:notice] %>
  <div>
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

<h1><%= @job.title %></h1>
<% if @job.disabled? %>
  <h2> Vaga desativada </h2>
<% end %>

<dl>
  <dt><%= Job.human_attribute_name(:description) %></dt>
  <dd><%= @job.description %></dd>

  <dt><%= Job.human_attribute_name(:requirements) %></dt>
  <dd><%= @job.requirements %></dd>

  <dt><%= Job.human_attribute_name(:level) %></dt>
  <dd><%= @job.level %></dd>

  <dt><%= Job.human_attribute_name(:remuneration) %></dt>
  <dd><%= number_to_currency(@job.remuneration) %></dd>

  <dt><%= Job.human_attribute_name(:spots_available) %></dt>
  <dd><%= @job.spots_available %></dd>

  <dt><%= Job.human_attribute_name(:expiration_date) %></dt>
  <dd><%= I18n.localize(@job.expiration_date) %></dd>
</dl>

<% unless recruiter_signed_in? %>
  <% if @job.candidates.include?(current_candidate) %>
    <% application = @job.job_applications.where(candidate: current_candidate).first %>
    <%= link_to "Acompanhar candidatura", job_application_path(application) %>
  <% else %>
    <%= link_to "Candidate-se para esta vaga", new_job_job_application_path(@job) %>
  <% end %>
<% end %>

<% if current_recruiter&.company == @job.company %>
  <%= link_to 'Editar vaga', edit_job_path %>
  <%= link_to 'Desativar vaga', disable_job_path(@job), method: :post unless @job.disabled? %>
  <%= link_to 'Ativar vaga', enable_job_path(@job), method: :post unless @job.enabled? %>
  <%= link_to 'Avaliar candidaturas', job_job_applications_path(@job) %>
<% end %>

<%= link_to 'Voltar', :back %>