config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'search', to: 'home#search'

  devise_for :recruiters, controllers: { registrations: 'recruiters/registrations' }
  resources :recruiters, only: %i[index]

  devise_for :candidates, controllers: { registrations: 'candidates/registrations' }
  resources :candidates, only: %i[index]
  
  resources :companies, except: [:new, :create, :destroy]
  resources :jobs, except: [:destroy] do
    shallow do
      resources :job_applications, except: [:edit, :update] do
        resources :rejections, only: [:index, :new, :create]
        resources :offers, only: [:show, :new, :create] do
          post 'accept', on: :member
          resources :denials, only: [:show, :new, :create]
        end
      end
    end
    post 'disable', on: :member
    post 'enable', on: :member
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def search
    query = params[:q]
    @companies = Company.where('name ilike ?', "%#{query}%")
    @jobs = Job.where('title ilike ? OR level ilike ?', "%#{query}%",
                      "%#{query}%")
  end
end

app/views/home/_search_form.html.erb
<%= form_with url: search_path, method: :get do %>
  <h4 class="text-center fw-light">
    <%= label_tag :q, 'Busque um cargo ou  empresa' %>
  </h4>
  <div class="input-group">
    <%= text_field_tag :q, nil, :class => "form-control form-control-lg" %>
    <%= submit_tag 'Pesquisar', :class => "btn btn-custom btn-lg" %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="container">
  <div class="row mt-md-5">
    <div class="col-12 col-md-6 order-2 order-md-1">

      <div class="row d-none d-md-block mt-5">
        <div class="col-12 d-flex justify-content-center">
          <h1 class="display=1 fw-light text-center">Encontre seu próximo trabalho em tecnologia!</h1>
        </div>
      </div>

      <div class="row mt-4">
        <div class="col-12 d-flex justify-content-center">
          <%= render 'search_form' %> 
        </div> 
      </div>

      <div class="row mt-4">
        <div class="col-6 d-flex justify-content-end">
          <%= link_to 'Vagas', jobs_path, :class => "btn btn-custom btn-lg" %>
        </div>
        <div class="col-6 d-flex justify-content-start">
          <%= link_to 'Empresas', companies_path, :class => "btn btn-custom btn-lg" %>
        </div>
      </div>

    </div>

    <div class="col-12 col-md-6 order-1 order-md-2">
      <%= image_tag("home_image.png", :class => "img-fluid", :alt => "Mulher entregando currículo") %>
    </div>
  </div>
</div>

app/views/home/search.html.erb
<h1 class="display-4 text-center mt-3">Resultados da busca:</h1>

<div class="container">
  <div class="container mt-5">
    <% if @companies.empty? %>
      <p>Nenhuma empresa encontrada com os termos buscados</p>
    <% else %>
      <h2>Empresas</h2>
      <% @companies.each do |company| %>
        <p><%= link_to company.name, company_path(company) %> - <%= company.website %></p>
      <% end %>
    <% end %>
  </div>

  <div class="container mt-5">
    <% if @jobs.empty? %>
      <p>Nenhuma vaga encontrada com os termos buscados</p>
    <% else %>
      <h2>Vagas</h2>
      <% @jobs.each do |job| %>
        <% unless job.disabled? %>
          <dl>
            <dt><%= Job.human_attribute_name(:title) %></dt>
            <dd>
              <%= link_to job.title, job_path(job) %>
              @ <%= link_to job.company.name, company_path(job.company) %>
            </dd>

            <dt><%= Job.human_attribute_name(:description) %></dt>
            <dd><%= job.description %></dd>

            <dt><%= Job.human_attribute_name(:level) %></dt>
            <dd><%= job.level %></dd>
          </dl>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <%= link_to 'Voltar', root_path %>
</div>