config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'search', to: 'home#search'

  devise_for :recruiters, controllers: { registrations: 'recruiters/registrations' }
  resources :recruiters, only: %i[index]

  devise_for :candidates, controllers: { registrations: 'candidates/registrations' }
  resources :candidates, only: %i[index]
  
  resources :companies, except: [:new, :create, :destroy]
  resources :jobs, except: [:destroy] do
    shallow do
      resources :job_applications, except: [:edit, :update] do
        resources :rejections, only: [:index, :new, :create]
        resources :offers, only: [:show, :new, :create] do
          post 'accept', on: :member
          resources :denials, only: [:show, :new, :create]
        end
      end
    end
    post 'disable', on: :member
    post 'enable', on: :member
  end
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  has_many :job_applications, dependent: :destroy
  has_many :jobs, through: :job_applications

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :full_name, :cpf, :bio, :email, presence: true
  validates :cpf, :email, uniqueness: true
end

app/controllers/candidates/registrations_controller.rb
# frozen_string_literal: true

class Candidates::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  # def edit
  #  super
  # end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[full_name social_name
                                                         cpf phone bio])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[full_name
                                                                social_name cpf
                                                                phone bio])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :authenticate_candidate!

  def index
    @job_applications = current_candidate.job_applications
  end
end

app/views/candidates/index.html.erb
<h1> Painel do candidato - <%= current_candidate.full_name %></h1>

<%= link_to 'Editar perfil', edit_candidate_registration_path %>
<%= link_to 'Encontrar vagas', jobs_path %>
<%= link_to 'Voltar', root_path %>

<% @job_applications.each do |application| %>
  <% if application.approved? && application.offer.accepted? %>
    <h2>Parabéns pela contratação!</h2>
    <p>Em breve a empresa entrará em contato com você para informar os próximos passos.</p>
  <% end %>
<% end %>

<h2>Ofertas recebidas: <%= @job_applications.approved.count %></h2>

<% @job_applications.each do |application| %>
  <% if application.approved? && application.offer.pending? %>
    <p><%= application.job.title %> - <%= application.job.company.name %> 
    <%= link_to 'Avaliar oferta', offer_path(application.offer) %></p>
    <hr>
  <% end %>
<% end %>

<h2>Minhas candidaturas: <%= @job_applications.pending.count %></h2>

<% @job_applications.each do |application| %>
  <% if application.pending? %>
    <p><%= application.job.title %> - <%= application.job.company.name %> 
    <%= link_to 'Acompanhar candidatura', job_application_path(application) %></p>
    <hr>
  <% end %>
<% end %>

<h2>Candidaturas rejeitadas: <%= @job_applications.rejected.count %></h2>

<% @job_applications.each do |application| %>
  <% if application.rejected? %>
    <p><%= application.job.title %> - <%= application.job.company.name %> 
    <hr>
  <% end %>
<% end %>