config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'search', to: 'home#search'

  devise_for :recruiters, controllers: { registrations: 'recruiters/registrations' }
  resources :recruiters, only: %i[index]

  devise_for :candidates, controllers: { registrations: 'candidates/registrations' }
  resources :candidates, only: %i[index]
  
  resources :companies, except: [:new, :create, :destroy]
  resources :jobs, except: [:destroy] do
    shallow do
      resources :job_applications, except: [:edit, :update] do
        resources :rejections, only: [:index, :new, :create]
        resources :offers, only: [:show, :new, :create] do
          post 'accept', on: :member
          resources :denials, only: [:show, :new, :create]
        end
      end
    end
    post 'disable', on: :member
    post 'enable', on: :member
  end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'TechJobs', root_path, :class => "navbar-brand" %>

    <div class="d-flex justify-content-end">
      <ul class="navbar-nav">
        <% if recruiter_signed_in? %>

          <li class="nav-item active">
            <%= link_to current_recruiter.email, recruiters_path, :class => "nav-link" %>
          </li>

          <li class="nav-item active">
            <%= link_to 'Sair', destroy_recruiter_session_path, method: :delete, :class => "nav-link" %>
          </li>

        <% elsif candidate_signed_in? %>

          <li class="nav-item">
            <%= link_to current_candidate.email, candidates_path, :class => "nav-link" %>
          </li>

          <li class="nav-item active">
            <%= link_to 'Sair', destroy_recruiter_session_path, method: :delete, :class => "nav-link" %>
          </li>

        <% else %>

          <li class="nav-item">
            <%= link_to 'Acesso candidatos', new_candidate_session_path, :class => "nav-link active" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Acesso recrutadores', new_recruiter_session_path, :class => "nav-link active" %>
          </li>

        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechJobs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Anonymous+Pro:wght@400;700&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
      <%= render 'layouts/nav' %>
    </header>

    <main class="container">
      <% if notice %>
        <p class="alert alert-primary mt-3" role="alert"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger mt-3" role="alert"><%= alert %></p>
      <% end %>
      
      <%= yield %>
    </main>
  </body>
</html>